cmake_minimum_required(VERSION 3.8)
project(ur10_sim_support)
find_package(ament_cmake REQUIRED)
find_package(gazebo REQUIRED)
find_package(gazebo_ros REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_srvs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
add_library(tim_demo_grasp SHARED src/demo_grasp.cpp)
target_compile_features(tim_demo_grasp PUBLIC cxx_std_17)
target_include_directories(tim_demo_grasp PRIVATE ${GAZEBO_INCLUDE_DIRS})
target_link_libraries(tim_demo_grasp ${GAZEBO_LIBRARIES})
ament_target_dependencies(tim_demo_grasp gazebo_ros rclcpp std_srvs std_msgs geometry_msgs)
install(TARGETS tim_demo_grasp DESTINATION lib)
install(DIRECTORY worlds DESTINATION share/${PROJECT_NAME})
ament_package()
