cmake_minimum_required(VERSION 3.8)
project(primitive_manager)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(pluginlib REQUIRED)

add_executable(primitive_manager src/manager.cpp)
target_compile_features(primitive_manager PUBLIC cxx_std_17)
target_compile_options(primitive_manager PRIVATE -Wall -Wextra -Wpedantic)
target_include_directories(primitive_manager PRIVATE include)
ament_target_dependencies(primitive_manager rclcpp std_msgs pluginlib)
install(TARGETS primitive_manager DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
ament_export_include_directories(include)
ament_export_dependencies(rclcpp)
ament_package()
