geometry_msgs/PoseStamped desired_pos   # configuration to reach
float64 max_vel 0.25                    # maximum velocity in m/s
bool immediate_execution false          # wether reaching the position has to be executed immediatly (cancelling all planned motions) or to be appended to the current motion queue
---
bool success
